### ISSUE TITLE
Cross: nothing happens for some programs

### ISSUE THREAD

**Issue by darkship** [divy-work/autopilot-deno#21]
deno --version
```
deno 1.0.5
v8 8.4.300
typescript 3.9.2
```
(I like this lib, thank you for building it)

I noticed when I tried to use `.tap` or `.type` nothing happens for some programs.

For example:
- `.tap`: IE and Firefox get into full screen mode with f11 or open the dev console with f12 but it's not triggered with autopilot. Whereas F12 triggers the definition search on VS Code.

- `.type`: trying to add some text into a login field or a chat field in a game like lineage2 doesn't show anything but it works with the browser search bar or a terminal.

Are there some known limitation or is that a bug?

**Comment by divy-work** [comment]
Autopilot does not know whether the text will be typed or not. It just simulates keypresses hoping that the input box is focused.

`.type` will work when the input is in focus. Since, in most games, the mouse pointer is hidden it is better to bring the chat field into focus using the game's key shortcuts and then type.

Interesting to know that `.tap` is not working on a browser window. Will try to reproduce the same.

**Comment by divy-work** [comment]
@darkship Unfortunately, I wasn't able to reproduce the issue with `.tap`. If you could provide a screencast or something, it'll be helpful. I'm closing this issue until there are more people facing the same issue.
You can always open up another one. Thanks a lot.
